### ISSUE TITLE
How to contribute to this project?

### ISSUE THREAD

**Issue by zengxinhai** [winfa/fresh-keeper#1]

**Comment by winfa** [comment]
always welcomed!

**Comment by winfa** [comment]
Welcome aboard again!! @zengxinhai

I will add  the basic info [here](https://github.com/winfa/fresh-keeper/issues/5). And all the questions or discussions could also be in Issues List.

I will add the basic mockup, user stories for the MVP. So everyone can update it or put comments there. 

I will also use the project board to do plans and identify what we need to do. So there will have a lot of things you can contribute to this project. You can:
- Review the mockup or user stories and the project planning. And contribute to the idea of the project. 
- Review PRs and contribute to the code quality. Or define the process which we can improve the process. 
- Take or submit cards.
